name: CI for ProjectOne

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    uses: saurang1984/dotnet-build-workflows/.github/workflows/dotnet-build.yml@main
    with:
      project-name: 'ProjectOne'
      solution-path: './ProjectOne.sln'
      dotnet-version: '8.0'
      secret-value: ${{ secrets.PROJECTONE_SECRET }}

